### ISSUE TITLE
alloc-dealloc-mismatch (malloc vs operator delete []) when using Realm::write_copy()

### ISSUE THREAD

**Issue by bdash** [realm/realm-object-store#339]
```
==2953==ERROR: AddressSanitizer: alloc-dealloc-mismatch (malloc vs operator delete []) on 0x625000007900
    #0 0x7f38db5b3caa in operator delete[](void*) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99caa)
    #1 0xa95046 in std::default_delete<char []>::operator()(char*) const /usr/include/c++/5/bits/unique_ptr.h:119
    #2 0xa8f68b in std::unique_ptr<char [], std::default_delete<char []> >::~unique_ptr() /usr/include/c++/5/bits/unique_ptr.h:484
    #3 0xc74513 in realm::OwnedData::~OwnedData() ../realm/owned_data.hpp:28
    #4 0xc7548d in realm::OwnedBinaryData::~OwnedBinaryData() ../realm/binary_data.hpp:127
    #5 0xc6c435 in ____C_A_T_C_H____T_E_S_T____429 tests/realm.cpp:441
    #6 0xb34840 in Catch::FreeFunctionTestCase::invoke() const tests/../external/catch/single_include/catch.hpp:6297
    #7 0xb0ff6b in Catch::TestCase::invoke() const tests/../external/catch/single_include/catch.hpp:7218
    #8 0xb32b5e in Catch::RunContext::invokeActiveTestCase() tests/../external/catch/single_include/catch.hpp:5891
    #9 0xb32557 in Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) tests/../external/catch/single_include/catch.hpp:5862
    #10 0xb2f925 in Catch::RunContext::runTest(Catch::TestCase const&) tests/../external/catch/single_include/catch.hpp:5687
    #11 0xb0ba9c in Catch::runTests(Catch::Ptr<Catch::Config> const&) tests/../external/catch/single_include/catch.hpp:6030
    #12 0xb33a69 in Catch::Session::run() tests/../external/catch/single_include/catch.hpp:6138
    #13 0xb3382b in Catch::Session::run(int, char const* const*) tests/../external/catch/single_include/catch.hpp:6117
    #14 0xb1a44e in main tests/../external/catch/single_include/catch.hpp:10027
    #15 0x7f38d9ecb82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #16 0x9b4458 in _start (/home/mrowe/source/realm-object-store/tests/tests+0x9b4458)

0x625000007900 is located 0 bytes inside of 8192-byte region [0x625000007900,0x625000009900)
allocated by thread T0 here:
    #0 0x7f38db5b2602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x154cee0 in realm::Group::write_to_mem() const /home/mrowe/source/realm-core/src/realm/group.cpp:812
    #2 0xf33399 in realm::Realm::write_copy() src/shared_realm.cpp:569
    #3 0xc6b9f2 in ____C_A_T_C_H____T_E_S_T____429 tests/realm.cpp:441
    #4 0xb34840 in Catch::FreeFunctionTestCase::invoke() const tests/../external/catch/single_include/catch.hpp:6297
    #5 0xb0ff6b in Catch::TestCase::invoke() const tests/../external/catch/single_include/catch.hpp:7218
    #6 0xb32b5e in Catch::RunContext::invokeActiveTestCase() tests/../external/catch/single_include/catch.hpp:5891
    #7 0xb32557 in Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) tests/../external/catch/single_include/catch.hpp:5862
    #8 0xb2f925 in Catch::RunContext::runTest(Catch::TestCase const&) tests/../external/catch/single_include/catch.hpp:5687
    #9 0xb0ba9c in Catch::runTests(Catch::Ptr<Catch::Config> const&) tests/../external/catch/single_include/catch.hpp:6030
    #10 0xb33a69 in Catch::Session::run() tests/../external/catch/single_include/catch.hpp:6138
    #11 0xb3382b in Catch::Session::run(int, char const* const*) tests/../external/catch/single_include/catch.hpp:6117
    #12 0xb1a44e in main tests/../external/catch/single_include/catch.hpp:10027
    #13 0x7f38d9ecb82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
```

We probably need to fix Core's `Group::write_to_mem` to use `operator new[]` and then return an `OwnedBinaryData`.

**Comment by fealebenpae** [comment]
@finnschiermer do you think this is still relevant?

**Comment by finnschiermer** [comment]
Fixed.
