### ISSUE TITLE
Sporadic sync test failure

### ISSUE THREAD

**Issue by austinzheng** [realm/realm-object-store#356]
Test fails as follows, after pulling in @morten-krogh's fixes to the notifier deadlock issue:

```
SyncSession: management by SyncUser
  sessions that were destroyed can be properly recreated when requested again
-------------------------------------------------------------------------------
tests/sync/session.cpp:79
...............................................................................

tests/sync/session.cpp:200: FAILED:
  REQUIRE( weak_session.expired() )
with expansion:
  false
```

and/or

```
SyncSession: management by SyncUser
  sessions that were destroyed can be properly recreated when requested again
-------------------------------------------------------------------------------
tests/sync/session.cpp:79
...............................................................................

tests/sync/session.cpp:206: FAILED:
  CHECK( session )
with expansion:
  false
```

Test failure is very rare; around once every 250 runs.

We hypothesize something related to the notifications code may be keeping the session alive longer than would be expected if the last reference to it was dropped when leaving the block scope. Using the runloop to wait for it to be destroyed fixes that bug.

We don't yet know why the second issue is happening. My hypothesis is that `sync` is reporting a particular error that puts the user in the `error` state around the time the session is being recreated, causing the user to return a null pointer instead of a pointer to a session.

cc @bdash

**Comment by austinzheng** [comment]
Another test failure:

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~/
root/realm-object-store/src/sync/sync_manager.cpp:451: [realm-core-2.3.0] Assertion failed: it != m_inactive_sessions.end()
IMPORTANT: if you see this error, please send this log to help@realm.io.
tests is a Catch v1.3.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
SyncSession: management by SyncUser
  sessions that were destroyed can be properly recreated when requested again
-------------------------------------------------------------------------------
/root/realm-object-store/tests/sync/session.cpp:79
...............................................................................

Thread name: tests/root/realm-object-store/tests/sync/session.cpp:208: FAILED:
  CHECK( session )

with expansion:
  false
  false

-------------------------------------------------------------------------------
SyncSession: management by SyncUser
-------------------------------------------------------------------------------
/root/realm-object-store/tests/sync/session.cpp:79
...............................................................................

/root/realm-object-store/tests/sync/session.cpp:181: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGABRT - Abort (abnormal termination) signal

===============================================================================
test cases:  1 |  0 passed | 1 failed
assertions: 22 | 20 passed | 2 failed
```

**Comment by austinzheng** [comment]
I finally captured a backtrace from gdb:

```
#0  0x00007ffff67a4428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff67a602a in __GI_abort () at abort.c:89
#2  0x0000000000fa31c3 in please_report_this_error_to_help_at_realm_dot_io () at util/terminate.cpp:46
#3  0x0000000000fa32c2 in realm::util::terminate_internal (ss=...) at util/terminate.cpp:123
#4  0x0000000000fa3492 in realm::util::terminate(char const*, char const*, long, std::initializer_list<realm::util::Printable>&&) (
    message=0x14a0324 "Assertion failed: !m_history", file=0x14a01c8 "../realm/noinst/client_file_access_cache.hpp", line=213, 
    values=<unknown type in /root/realm-object-store/tests/tests, CU 0x1a4b6a3, DIE 0x1a506a1>) at util/terminate.cpp:140
#5  0x0000000000f83a4f in realm::_impl::ClientFileAccessCache::Slot::is_open (this=0x19acc10)
    at ../realm/noinst/client_file_access_cache.hpp:213
#6  0x0000000000f83832 in realm::_impl::ClientFileAccessCache::Slot::close (this=0x19acc10)
    at ../realm/noinst/client_file_access_cache.hpp:198
#7  0x0000000000f65d18 in (anonymous namespace)::SessionImpl::terminate (this=0x19acbf0) at sync/client.cpp:766
#8  0x0000000000f6bd11 in (anonymous namespace)::ClientImpl::register_abandoned_session (this=0x19b07e0, sess=...) at sync/client.cpp:2201
#9  0x0000000000f71350 in realm::sync::Session::~Session (this=0x19acbd0, __in_chrg=<optimized out>) at sync/client.cpp:3319
#10 0x0000000000eabf40 in std::default_delete<realm::sync::Session>::operator() (this=0x19acaa8, __ptr=0x19acbd0)
    at /usr/include/c++/5/bits/unique_ptr.h:76
#11 0x0000000000eb6ffb in std::unique_ptr<realm::sync::Session, std::default_delete<realm::sync::Session> >::reset (this=0x19acaa8, 
    __p=0x19acbd0) at /usr/include/c++/5/bits/unique_ptr.h:344
#12 0x0000000000eb656f in std::unique_ptr<realm::sync::Session, std::default_delete<realm::sync::Session> >::operator=(decltype(nullptr)) (
    this=0x19acaa8) at /usr/include/c++/5/bits/unique_ptr.h:280
#13 0x0000000000eb5842 in realm::_impl::sync_session_states::Inactive::enter_state (
    this=0x195d700 <reference temporary #3 for realm::SyncSession::State::inactive>, lock=..., session=...)
    at /root/realm-object-store/src/sync/sync_session.cpp:250
#14 0x0000000000eb26bb in realm::SyncSession::advance_state (this=0x19ac8f0, lock=..., state=...)
    at /root/realm-object-store/src/sync/sync_session.cpp:529
#15 0x0000000000eb5535 in realm::_impl::sync_session_states::Active::log_out (
    this=0x195d6f0 <reference temporary #1 for realm::SyncSession::State::active>, lock=..., session=...)
    at /root/realm-object-store/src/sync/sync_session.cpp:195
#16 0x0000000000eb29c7 in realm::SyncSession::log_out (this=0x19ac8f0) at /root/realm-object-store/src/sync/sync_session.cpp:556
#17 0x0000000000eb9f77 in realm::SyncUser::log_out (this=0x19b4670) at /root/realm-object-store/src/sync/sync_user.cpp:142
#18 0x0000000000d1bb60 in ____C_A_T_C_H____T_E_S_T____79 () at /root/realm-object-store/tests/sync/session.cpp:125
#19 0x0000000000ae837c in Catch::FreeFunctionTestCase::invoke (this=0x1973aa0)
    at /root/realm-object-store/tests/../external/catch/single_include/catch.hpp:6297
#20 0x0000000000ad2e29 in Catch::TestCase::invoke (this=0x19a5640)
    at /root/realm-object-store/tests/../external/catch/single_include/catch.hpp:7218
#21 0x0000000000ae72de in Catch::RunContext::invokeActiveTestCase (this=0x7fffffffdb40)
    at /root/realm-object-store/tests/../external/catch/single_include/catch.hpp:5891
#22 0x0000000000ae6f6b in Catch::RunContext::runCurrentTest (this=0x7fffffffdb40, redirectedCout="", redirectedCerr="")
    at /root/realm-object-store/tests/../external/catch/single_include/catch.hpp:5862
#23 0x0000000000ae583f in Catch::RunContext::runTest (this=0x7fffffffdb40, testCase=...)
    at /root/realm-object-store/tests/../external/catch/single_include/catch.hpp:5687
#24 0x0000000000ad0368 in Catch::runTests (config=...) at /root/realm-object-store/tests/../external/catch/single_include/catch.hpp:6030
#25 0x0000000000ae7bec in Catch::Session::run (this=0x7fffffffde60)
    at /root/realm-object-store/tests/../external/catch/single_include/catch.hpp:6138
#26 0x0000000000ae7ade in Catch::Session::run (this=0x7fffffffde60, argc=2, argv=0x7fffffffe0a8)
    at /root/realm-object-store/tests/../external/catch/single_include/catch.hpp:6117
#27 0x0000000000ad93ea in main (argc=2, argv=0x7fffffffe0a8)
    at /root/realm-object-store/tests/../external/catch/single_include/catch.hpp:10027
```

Will analyze it next week.

**Comment by kspangsege** [comment]
@austinzheng The stack trace above is definitely the same kind of issue as e.g. https://github.com/realm/realm-object-store/issues/462. This was resolved recently by https://github.com/realm/realm-sync/pull/1391.

**Comment by austinzheng** [comment]
I'm going to close this ticket; if the bug somehow re-appears I'll file a new one with updated information.
